apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atlas-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: atlas-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atlas-api-svc
                port:
                  number: 80