apiVersion: batch/v1
kind: Job
metadata:
  name: atlas-migrate-job
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: postgres-ready
          image: postgres:alpine
          command:
            - "sh"
            - "-c"
            - "until pg_isready -h postgres -p 5432; do sleep 2; done"
      containers:
        - name: atlas-migrate
          image: "ghcr.io/ankurdubey28/atlas-migrate:{{ .Values.images.migrate.tag }}"

          envFrom:
            - secretRef:
                name: atlas-secrets

          env:
            - name: GOOSE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: atlas-cm
                  key: GOOSE_DRIVER

            - name: GOOSE_MIGRATION_DIR
              valueFrom:
                configMapKeyRef:
                  name: atlas-cm
                  key: GOOSE_MIGRATION_DIR

          args:
            - "-dir"
            - "$(GOOSE_MIGRATION_DIR)"
            - "up"

  backoffLimit: 4
