version: '3'

vars:
  PLATFORM: linux/amd64
  IMAGE_NAME: atlas-platform
  CONTAINER_NAME: atlas-platform
  TAG: 1.0.0

tasks:
  build-api:
    desc: build image for {{.PLATFORM}} architecture
    cmd: docker compose build api

  run-api:
    desc: run container for image {{.PLATFORM}}
    cmd: docker compose up -d api

  run-db:
    desc: run postgres container
    cmd: docker compose up -d postgres

  apply-migrations:
    desc: apply goose migrations by starting container
    cmd: docker compose run --rm migrate


  up:
    desc: One-click local development setup
    cmds:
      - task: build-api
      - task: run-db
      - task: apply-migrations
      - task: run-api


  clean:
    desc: Stop and remove all containers, networks, and volumes
    cmd: docker compose down -v