images:
  api:
    repository: ankur2803/atlas-api
    tag: "30739930066"
    pullPolicy: IfNotPresent
  migrate:
    repository: ankur2803/atlas-migrate
    tag: "30739930066"
    pullPolicy: IfNotPresent

